modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"

[[mods]]
modId="lava_rain"
version="1.0.0"
displayName="Nether Lava Rain"
description="For contents!"
authors="SteveKunG"

[[dependencies.lava_rain]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lava_rain]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lava_rain]]
    modId="stevekungs_lib"
    mandatory=true
    versionRange="[4.0.0,)"
    ordering="NONE"
    side="BOTH"